Repository alkong-dalkong/alkong-dalkong_fe, pull requests merged in 2024-08, with the labels that each got.

#24 chore : mint-0 색상 추가
  src/styles/color.ts
Labels: chore

#32 fix : 페이지 스크롤 안되는 문제 해결
  .pnp.cjs
  .yarn/cache/tailwind-scrollbar-hide-npm-1.1.7-537baa5b75-1027ca724c.zip
  package.json
  src/app/layout.tsx
  tailwind.config.ts
  yarn.lock
Labels: fix

#35 feat : 토글 버튼 구현
  .pnp.cjs
  .yarn/cache/use-sync-external-store-npm-1.2.2-7923c915e1-23b1597c10.zip
  .yarn/cache/zustand-npm-4.5.5-678823f519-d04469d76b.zip
  package.json
  src/components/toggle/Toggle.stories.tsx
  src/components/toggle/Toggle.tsx
  src/hooks/useToggle.ts
  yarn.lock
Labels: feat

#46 fix : 스토리북 Toggle 매개변수명 수정
  src/components/toggle/Toggle.stories.tsx
Labels: fix

#45 feat: Icon 컴포넌트 추가
  src/components/icons/Arrow.tsx
  src/components/icons/Check.tsx
  src/components/icons/Close.tsx
  src/components/icons/Label.tsx
  src/components/icons/Minus.tsx
  src/components/icons/Navi.tsx
  src/components/icons/Plus.tsx
  src/components/icons/index.stories.tsx
  src/components/icons/index.tsx
Labels: feat

#49 chore : 리액트 훅 폼 설치
  .pnp.cjs
  .yarn/cache/react-hook-form-npm-7.52.2-7602393eb2-2b8d37239d.zip
  package.json
  yarn.lock
Labels: chore

#54 feat: Bottom Sheet 컴포넌트 추가
  .github/workflows/storybook.yml
  .pnp.cjs
  .yarn/cache/framer-motion-npm-11.3.29-f5a8e85978-f60d9bbeca.zip
  package.json
  src/app/layout.tsx
  src/components/bottomSheet/BottomSheet.stories.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/icons/Bar.tsx
  src/components/icons/index.tsx
  src/components/portal/AnimatePortal.tsx
  src/components/portal/Portal.tsx
  src/constants/.gitkeep
  src/constants/index.ts
  src/constants/zIndex.ts
  src/hooks/Hydration.tsx
  src/hooks/LazyMotionProvider.tsx
  src/hooks/QueryProvider.tsx
  src/hooks/index.ts
  src/hooks/useScrollLock.tsx
  yarn.lock
Labels: feat

#57 fix: github action 에러 해결
  .github/workflows/develop-push-action.yml
  .github/workflows/main-push-action.yml
Labels: fix

#56 fix : useToggle 훅에 'use client' 선언 추가
  src/hooks/useToggle.ts
Labels: fix

#67 chore: vercel deployment 워크플로우 수정
  .github/workflows/develop-push-action.yml
  .github/workflows/main-push-action.yml
Labels: chore

#68 chore: 기존 워크플로우 제거 및 새 vercel deployment 워크플로우 추가
  .github/workflows/deployment.yml
  .github/workflows/develop-push-action.yml
  .github/workflows/main-push-action.yml
  build.sh
Labels: chore

#70 fix : 스토리북 폰트 문제 해결
  .storybook/preview.tsx
  public/app/font.ts
  src/app/layout.tsx
Labels: fix

#43 feat: action button component
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
Labels: feat

#74 feat: 프로필 컴포넌트 추가
  src/components/icons/Ellipse.tsx
  src/components/icons/index.tsx
  src/components/profile/Profile.stories.tsx
  src/components/profile/Profile.tsx
Labels: feat

#64 feat : 슬라이더 구현
  .pnp.cjs
  package.json
  src/components/slider/Slider.stories.tsx
  src/components/slider/Slider.tsx
  src/components/slider/TimeSlider.tsx
  src/components/slider/WeightSlider.tsx
  src/constants/index.ts
  src/constants/slide.ts
  src/hooks/index.ts
  src/hooks/useDebounceCallback.ts
  src/store/timeStore.ts
  src/store/weightStore.ts
  yarn.lock
Labels: feat

#29 feat: Tag Component & ActionTag Component
  .yarn/cache/workbox-background-sync-npm-6.6.0-9d7253959c-204410fc33.zip
  .yarn/cache/workbox-broadcast-update-npm-6.6.0-f36dfd50b0-a10bdaae57.zip
  .yarn/cache/workbox-build-npm-6.6.0-3d8f742cc2-d13d9757d5.zip
  .yarn/cache/workbox-cacheable-response-npm-6.6.0-bc02dc9e67-90d6fa76e5.zip
  .yarn/cache/workbox-core-npm-6.6.0-498740a171-c8fc7b1bc2.zip
  .yarn/cache/workbox-expiration-npm-6.6.0-f36fa69708-29c7b11fab.zip
  .yarn/cache/workbox-google-analytics-npm-6.6.0-9b5d2fcb5c-e1e45eab37.zip
  .yarn/cache/workbox-navigation-preload-npm-6.6.0-ad8c127b21-1bf6be2c76.zip
  .yarn/cache/workbox-precaching-npm-6.6.0-6cdfaf7063-73773def12.zip
  .yarn/cache/workbox-range-requests-npm-6.6.0-15fcc8d8e9-3a25bc879a.zip
  .yarn/cache/workbox-recipes-npm-6.6.0-d532be2448-e0f92d2aba.zip
  .yarn/cache/workbox-routing-npm-6.6.0-4f121cf6d1-28a204a86a.zip
  .yarn/cache/workbox-strategies-npm-6.6.0-a13474e906-ba61b00d36.zip
  .yarn/cache/workbox-streams-npm-6.6.0-49d9d92ad1-67b7c8a69c.zip
  .yarn/cache/workbox-sw-npm-6.6.0-c45bc0a01e-e2388125ae.zip
  .yarn/cache/workbox-webpack-plugin-npm-6.6.0-b93fc3a428-ade1388545.zip
  .yarn/cache/workbox-window-npm-6.6.0-e9667fec2c-7e3fdfaa9d.zip
  src/components/actionTag/ActionTag.stories.tsx
  src/components/actionTag/ActionTag.tsx
  src/components/tag/Tag.stories.tsx
  src/components/tag/Tag.tsx
Labels: feat

#81 fix : InputGroup CheckBox 화살표 클릭 시, 이벤트 추가
  src/components/inputGroup/CheckBox.tsx
  src/components/inputGroup/InputGroup.stories.tsx
Labels: fix

#76 feat: BottomNav 컴포넌트 추가
  src/app/clinic/[userId]/page.tsx
  src/app/health/[userId]/page.tsx
  src/app/home/[userId]/page.tsx
  src/app/layout.tsx
  src/app/medicine/[userId]/page.tsx
  src/components/.gitkeep
  src/components/bottomNav/BottomNav.stories.tsx
  src/components/bottomNav/BottomNav.tsx
  src/components/bottomSheet/BottomSheet.tsx
  src/components/index.ts
  src/components/portal/Portal.tsx
  src/components/profile/Profile.tsx
  src/components/profile/ProfileModal.tsx
  src/constants/zIndex.ts
  src/store/.gitkeep
  src/store/index.ts
  src/store/userStore.ts
  src/types/.gitkeep
  src/types/index.ts
  src/types/user.ts
Labels: feat

#86 fix : SignupForm 스토리북 onClickArrow props 추가
  src/schema/stories/SignupForm.stories.tsx
  src/types/index.ts
Labels: fix

#75 feat: 캘린더 컴포넌트
  src/components/calendar/Calendar.stories.tsx
  src/components/calendar/Calendar.tsx
  src/components/calendar/DateBox.tsx
  src/components/calendar/DateBoxList.tsx
  src/components/calendar/DateList.tsx
  src/components/calendar/EmptyDateBoxList.tsx
  src/components/calendar/MonthNavigator.tsx
  src/components/calendar/WeekList.tsx
  src/store/calendarStore.ts
  src/utils/validateTheme.ts
Labels: feat

#79 fix : Label 및 Toggle 컴포넌트 수정
  src/components/actionTag/ActionTag.stories.tsx
  src/components/label/Label.stories.tsx
  src/components/label/Label.tsx
  src/components/tag/Tag.stories.tsx
  src/components/toggle/Toggle.stories.tsx
Labels: fix

#87 fix : 이미지 속성들 camelCase로 변경
  src/components/icons/Arrow.tsx
  src/components/icons/Check.tsx
  src/components/icons/Close.tsx
  src/components/icons/Minus.tsx
  src/components/icons/Plus.tsx
Labels: fix

#77 feat: Header 컴포넌트 추가
  .storybook/preview.tsx
  src/components/header/Header.stories.tsx
  src/components/header/MainHeader.tsx
  src/components/header/SubHeader.tsx
Labels: feat

#91 fix: BottomNav 컴포넌트 수정
  src/app/clinic/[userId]/page.tsx
  src/app/health/[userId]/page.tsx
  src/app/home/[userId]/page.tsx
  src/app/layout.tsx
  src/app/medicine/[userId]/page.tsx
  src/components/bottomNav/BottomNav.tsx
  src/components/profile/ProfileModal.tsx
Labels: fix

#92 feat: Header 컴포넌트 내 useUserStore 적용
  src/components/header/MainHeader.tsx
Labels: feat
